version: "3.8"
services:
  postgres:
    image: postgres:13.3-alpine
    env_file:
      - .env
    # environment:
    #   - POSTGRES_USER=user
    #   - POSTGRES_PASSWORD=password
    # volumes:
    #   - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
